version: '3.8'

x-app-service: &default-app
  build: .
  command: ''
  environment:
    - MONGO_URL=mongodb://mongo:27017/dev
  depends_on:
    - mongo
  volumes:
    - .:/code:delegated
    - node_modules:/code/node_modules:delegated

services:
  app:
    <<: *default-app

  backend:
    <<: *default-app
    command: bash -c "npm run dev"
    ports:
      - 5000:5000

  frontend:
    <<: *default-app
    command: bash -c "cd ./src/apps/CryptoWars/frontend && npm install && npm run dev"
    ports:
      - 3000:3000

#  mongo:
#    image: mongo:3.4.6
#    volumes:
#      - ./data/mongo:/data/db:delegated
#    ports:
#      - 27017:27017

volumes:
  node_modules:
  esdata:
    driver: local
