services:

  Battlefield.Armies.ArmyRepository:
    class: ../../../../../Contexts/Battlefield/Armies/Infrastructure/Persistence/SqliteArmyRepository
    arguments: [ '@Shared.ConnectionManager' ]

  Battlefield.Armies.CreateArmy:
    class: ../../../../../Contexts/Battlefield/Armies/Application/Create/CreateArmy
    arguments: [ '@Battlefield.Armies.ArmyRepository', '@Shared.EventBus' ]

  Battlefield.Armies.CreateArmyOnTownCreated:
    class: ../../../../../Contexts/Battlefield/Armies/Application/Create/CreateArmyOnTownCreated
    arguments: [ '@Battlefield.Armies.CreateArmy' ]
    tags:
      - { name: 'domainEventSubscriber' }

  Battlefield.Armies.FindArmyByTown:
    class: ../../../../../Contexts/Battlefield/Armies/Application/Find/FindArmyByTown
    arguments: [ '@Battlefield.Armies.ArmyRepository' ]

  Battlefield.Armies.FindArmyByTownQueryHandler:
    class: ../../../../../Contexts/Battlefield/Armies/Application/Find/FindArmyByTownQueryHandler
    arguments: [ '@Battlefield.Armies.FindArmyByTown' ]
    tags:
      - { name: 'queryHandler' }
