services:

  Battlefield.Armies.ArmyRepository:
    class: ../../../../../Contexts/Battlefield/Armies/Infrastructure/Persistence/SqliteArmyRepository
    arguments: [ '@Shared.ConnectionManager' ]

  Battlefield.Shared.BattlefieldInternalEventRepository:
    class: ../../../../../Contexts/Battlefield/Shared/Infrastructure/Persistence/SqliteBattlefieldEventRepository
    arguments: [ '@Shared.ConnectionManager' ]

  Battlefield.Armies.CreateArmy:
    class: ../../../../../Contexts/Battlefield/Armies/Application/Create/CreateArmy
    arguments: [ '@Battlefield.Armies.ArmyRepository','@Battlefield.Shared.BattlefieldInternalEventRepository', '@Shared.EventBus' ]

  Battlefield.Armies.CreateArmyOnTownCreated:
    class: ../../../../../Contexts/Battlefield/Armies/Application/Create/CreateArmyOnTownCreated
    arguments: [ '@Battlefield.Armies.CreateArmy' ]
    tags:
      - { name: 'domainEventSubscriber' }

  Battlefield.Armies.FindArmyByTown:
    class: ../../../../../Contexts/Battlefield/Armies/Application/Find/FindArmyByTown
    arguments: [ '@Battlefield.Armies.ArmyRepository' ]

  Battlefield.Armies.FindArmyByTownQueryHandler:
    class: ../../../../../Contexts/Battlefield/Armies/Application/Find/FindArmyByTownQueryHandler
    arguments: [ '@Battlefield.Armies.FindArmyByTown' ]
    tags:
      - { name: 'queryHandler' }

  Battlefield.Armies.RecruitSquad:
    class: ../../../../../Contexts/Battlefield/Armies/Application/Recruit/RecruitSquad
    arguments: [ '@Battlefield.Armies.ArmyRepository','@Battlefield.Shared.BattlefieldInternalEventRepository', '@Shared.EventBus' ]

  Battlefield.Armies.RecruitSoldiersOnTownSoldiersTrainFinished:
    class: ../../../../../Contexts/Battlefield/Armies/Application/Recruit/RecruitSquadOnTownSoldiersTrainFinished
    arguments: [ '@Battlefield.Armies.RecruitSquad' ]
    tags:
      - { name: 'domainEventSubscriber' }
