services:

  CryptoWars.Towns.TownRepository:
    class: ../../../../../Contexts/CryptoWars/Towns/Infrastructure/Persistence/SqliteTownRepository
    arguments: [ '@Shared.ConnectionManager' ]

  CryptoWars.Towns.TrainSoldiers:
    class: ../../../../../Contexts/CryptoWars/Towns/Application/TrainSoldiers
    arguments: [ '@CryptoWars.Towns.TownRepository', '@Shared.EventBus' ]

  CryptoWars.Towns.TrainSoldiersCommandHandler:
    class: ../../../../../Contexts/CryptoWars/Towns/Application/TrainSoldiersCommandHandler
    arguments: [ '@CryptoWars.Towns.TrainSoldiers' ]
    tags:
      - { name: 'commandHandler' }
