services:

  CryptoWars.Users.UserRepository:
    class: ../../../../../Contexts/CryptoWars/Users/Infrastructure/Persistence/InMemoryUserRepository

  CryptoWars.Users.CreateUser:
    class: ../../../../../Contexts/CryptoWars/Users/Application/Create/CreateUser
    arguments: ['@CryptoWars.Users.UserRepository', '@Shared.EventBus']

  CryptoWars.Users.CreateUserCommandHandler:
    class: ../../../../../Contexts/CryptoWars/Users/Application/Create/CreateUserCommandHandler
    arguments: ['@CryptoWars.Users.CreateUser']
    tags:
      - { name: 'commandHandler' }
