services:

  Battlefield.Battles.ListBattlesByArmyId:
    class: ../../../../../../Contexts/Battlefield/Battles/Application/List/ListBattlesByArmyId
    arguments: [ '@Battlefield.Shared.BattlefieldInternalEventRepository' ]

  Battlefield.Battles.ListBattlesByArmyIdQueryHandler:
    class: ../../../../../../Contexts/Battlefield/Battles/Application/List/ListBattlesByArmyIdQueryHandler
    arguments: [ '@Battlefield.Battles.ListBattlesByArmyId' ]
    tags:
      - { name: 'queryHandler' }

  Battlefield.Battles.CreateBattle:
    class: ../../../../../../Contexts/Battlefield/Battles/Application/Create/CreateBattle
    arguments: [ '@Battlefield.Shared.BattlefieldInternalEventRepository', '@Shared.EventBus' ]

  Battlefield.Battles.CreateBattleOnAttackArrived:
    class: ../../../../../../Contexts/Battlefield/Battles/Application/Create/CreateBattleOnAttackArrived
    arguments: [ '@Battlefield.Battles.CreateBattle' ]
    tags:
      - { name: 'domainEventSubscriber' }

