services:

  Battlefield.Attacks.SendAttack:
    class: ../../../../../Contexts/Battlefield/Attacks/Application/Send/SendAttack
    arguments: [ '@Battlefield.Shared.BattlefieldInternalEventRepository','@Shared.QueryBus', '@Shared.EventBus' ]

  Battlefield.Attacks.SendAttackCommandHandler:
    class: ../../../../../Contexts/Battlefield/Attacks/Application/Send/SendAttackCommandHandler
    arguments: [ '@Battlefield.Attacks.SendAttack' ]
    tags:
      - { name: 'commandHandler' }

