services:

  Apps.CryptoWars.Backend.Controllers.StatusGetController:
    class: ../../Controllers/StatusGetController
    arguments: [ ]

  Apps.CryptoWars.Backend.Controllers.UsersPutController:
    class: ../../Controllers/IAM/Users/UsersPutController
    arguments: [ '@Shared.CommandBus' ]

  Apps.CryptoWars.Backend.Controllers.WorldsGetController:
    class: ../../Controllers/CryptoWars/Worlds/WorldsGetController
    arguments: [ '@Shared.QueryBus' ]

  Apps.CryptoWars.Backend.Controllers.WorldGetController:
    class: ../../Controllers/CryptoWars/Worlds/WorldGetController
    arguments: [ '@Shared.QueryBus' ]

  Apps.CryptoWars.Backend.Controllers.JoinWorldPutController:
    class: ../../Controllers/CryptoWars/Worlds/JoinWorldPutController
    arguments: [ '@Shared.CommandBus' ]

  Apps.CryptoWars.Backend.Controllers.PlayerGetController:
    class: ../../Controllers/CryptoWars/Players/PlayerGetController
    arguments: [ '@Shared.QueryBus' ]

  Apps.CryptoWars.Backend.Controllers.TrainSoldiersPostController:
    class: ../../Controllers/CryptoWars/Towns/TrainSoldiersPostController
    arguments: [ '@Shared.CommandBus' ]

  Apps.Battlefield.Backend.Controllers.ArmyGetController:
    class: ../../Controllers/Battlefield/Armies/ArmyGetController
    arguments: [ '@Shared.QueryBus' ]

  Apps.Battlefield.Backend.Controllers.SendAttackPutController:
    class: ../../Controllers/Battlefield/Attacks/SendAttackPutController
    arguments: [ '@Shared.CommandBus' ]

  Apps.Battlefield.Backend.Controllers.BattlesGetController:
    class: ../../Controllers/Battlefield/Battles/BattlesGetController
    arguments: [ '@Shared.QueryBus' ]
