services:

  Apps.CryptoWars.Backend.Controllers.StatusGetController:
    class: ../../Controllers/StatusGetController
    arguments: []

  Apps.CryptoWars.Backend.Controllers.UsersPutController:
    class: ../../Controllers/UsersPutController
    arguments: ['@Shared.CommandBus']

