services:

  Apps.CryptoWars.Backend.Controllers.StatusGetController:
    class: ../../Controllers/StatusGetController
    arguments: [ ]

  Apps.CryptoWars.Backend.Controllers.UsersPutController:
    class: ../../Controllers/Users/UsersPutController
    arguments: [ '@Shared.CommandBus' ]

  Apps.CryptoWars.Backend.Controllers.WorldsGetController:
    class: ../../Controllers/Worlds/WorldsGetController
    arguments: [ '@Shared.QueryBus' ]

  Apps.CryptoWars.Backend.Controllers.JoinWorldPutController:
    class: ../../Controllers/Worlds/JoinWorldPutController
    arguments: [ '@Shared.CommandBus' ]

  Apps.CryptoWars.Backend.Controllers.PlayerGetController:
    class: ../../Controllers/Players/PlayerGetController
    arguments: [ '@Shared.QueryBus' ]

  Apps.CryptoWars.Backend.Controllers.TrainSoldiersPostController:
    class: ../../Controllers/Towns/TrainSoldiersPostController
    arguments: [ '@Shared.CommandBus' ]

  Apps.Battlefield.Backend.Controllers.ArmyGetController:
    class: ../../Controllers/Armies/ArmyGetController
    arguments: [ '@Shared.QueryBus' ]

  Apps.Battlefield.Backend.Controllers.SendAttackPutController:
    class: ../../Controllers/Attacks/SendAttackPutController
    arguments: [ '@Shared.CommandBus' ]

