services:

  Scheduler.Tasks.TaskRepository:
    class: ../../../../../../Contexts/Scheduler/Tasks/Infrastructure/Persistence/SqliteTaskRepository
    arguments: [ '@Scheduler.ConnectionManager' ]

  Scheduler.Tasks.CreateTask:
    class: ../../../../../../Contexts/Scheduler/Tasks/Application/Create/CreateTask
    arguments: [ '@Scheduler.Tasks.TaskRepository', '@Shared.EventBus' ]

  Scheduler.Tasks.CreateTaskOnTaskRequested:
    class: ../../../../../../Contexts/Scheduler/Tasks/Application/Create/CreateTaskOnTaskRequested
    arguments: [ '@Scheduler.Tasks.CreateTask' ]
    tags:
      - { name: 'domainEventSubscriber' }

  Scheduler.Tasks.ExecuteTasksPreviousTo:
    class: ../../../../../../Contexts/Scheduler/Tasks/Application/Execute/ExecuteTasksPreviousTo
    arguments: [ '@Scheduler.Tasks.TaskRepository', '@Shared.EventBus' ]

  Scheduler.Tasks.ExecuteTasksPreviousToCommandHandler:
    class: ../../../../../../Contexts/Scheduler/Tasks/Application/Execute/ExecuteTasksPreviousToCommandHandler
    arguments: [ '@Scheduler.Tasks.ExecuteTasksPreviousTo' ]
    tags:
      - { name: 'commandHandler' }
