services:

  Shared.QueryHandlersInformation:
    class: ../../../../../Contexts/Shared/Infrastructure/QueryBus/QueryHandlersInformation
    arguments: [ '!tagged queryHandler' ]

  Shared.QueryBus:
    class: ../../../../../Contexts/Shared/Infrastructure/QueryBus/InMemoryQueryBus
    arguments: [ '@Shared.QueryHandlersInformation' ]

  Shared.CommandHandlersInformation:
    class: ../../../../../Contexts/Shared/Infrastructure/CommandBus/CommandHandlersInformation
    arguments: [ '!tagged commandHandler' ]

  Shared.CommandBus:
    class: ../../../../../Contexts/Shared/Infrastructure/CommandBus/InMemoryCommandBus
    arguments: [ '@Shared.CommandHandlersInformation' ]

  Shared.Logger:
    class: ../../../../../Contexts/Shared/Infrastructure/WinstonLogger
    arguments: [ ]

  Shared.EventBus:
    class: ../../../../../Contexts/Shared/Infrastructure/EventBus/InMemory/InMemoryAsyncEventBus
    arguments: [ ]

  Shared.TypeOrmConfig:
    factory:
      class: ../../../../../Contexts/CryptoWars/Shared/Infrastructure/Persistence/Sqlite/TypeOrmConfigFactory
      method: 'createConfig'

  Shared.ConnectionManager:
    factory:
      class: ../../../../../Contexts/Shared/Infrastructure/Persistence/Sqlite/TypeOrmClientFactory
      method: 'createClient'
    arguments: [ 'Shared', '@Shared.TypeOrmConfig' ]

  Scheduler.TypeOrmConfig:
    factory:
      class: ../../../../../Contexts/Scheduler/Shared/Infrastructure/Persistence/Sqlite/TypeOrmConfigFactory
      method: 'createConfig'

  Scheduler.ConnectionManager:
    factory:
      class: ../../../../../Contexts/Shared/Infrastructure/Persistence/Sqlite/TypeOrmClientFactory
      method: 'createClient'
    arguments: [ 'Scheduler', '@Scheduler.TypeOrmConfig' ]
