services:

  Shared.QueryHandlersInformation:
    class: ../../../../../Contexts/Shared/Infrastructure/QueryBus/QueryHandlersInformation
    arguments: ['!tagged queryHandler']

  Shared.QueryBus:
    class: ../../../../../Contexts/Shared/Infrastructure/QueryBus/InMemoryQueryBus
    arguments: ['@Shared.QueryHandlersInformation']

  Shared.CommandHandlersInformation:
    class: ../../../../../Contexts/Shared/Infrastructure/CommandBus/CommandHandlersInformation
    arguments: ['!tagged commandHandler']

  Shared.CommandBus:
    class: ../../../../../Contexts/Shared/Infrastructure/CommandBus/InMemoryCommandBus
    arguments: ['@Shared.CommandHandlersInformation']

  Shared.Logger:
    class: ../../../../../Contexts/Shared/Infrastructure/WinstonLogger
    arguments: []

  Shared.EventBus:
    class: ../../../../../Contexts/Shared/infrastructure/EventBus/InMemory/InMemorySyncEventBus
    arguments: []
