imports:
  - { resource: ./Apps/application.yaml }
  - { resource: ./Shared/application.yaml }
  - { resource: ./Users/application.yaml }
  - { resource: ./Players/application.yaml }
  - { resource: ./Worlds/application.yaml }
  - { resource: ./Towns/application.yaml }
  - { resource: ./Armies/application.yaml }
  - { resource: ./Attacks/application.yaml }
