imports:
  - { resource: ./application.yaml }

services:
  CryptoWars.EnvironmentArranger:
    class: ../../../../../tests/Contexts/Shared/infrastructure/Persistence/InMemoryEnvironmentArranger

  Shared.EventBus:
    class: ../../../../Contexts/Shared/infrastructure/EventBus/InMemory/InMemorySyncEventBus
    arguments: []
