imports:
  - { resource: ./application.yaml }

services:
  CryptoWars.EnvironmentArranger:
    class: ../../../../../tests/Contexts/Shared/infrastructure/Persistence/TypeOrmEnvironmentArranger
    arguments: [ '@Shared.ConnectionManager' ]
